// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: health/health_serice.proto

package health

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_health_health_serice_proto protoreflect.FileDescriptor

const file_health_health_serice_proto_rawDesc = "" +
	"\n" +
	"\x1ahealth/health_serice.proto\x12\x06health\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto2Y\n" +
	"\rHealthService\x12H\n" +
	"\x05Check\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB5Z3github.com/partaudit-fr/grpc-lib/protogen/go/healthb\x06proto3"

var file_health_health_serice_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_health_health_serice_proto_depIdxs = []int32{
	0, // 0: health.HealthService.Check:input_type -> google.protobuf.Empty
	0, // 1: health.HealthService.Check:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_health_serice_proto_init() }
func file_health_health_serice_proto_init() {
	if File_health_health_serice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_health_serice_proto_rawDesc), len(file_health_health_serice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_health_serice_proto_goTypes,
		DependencyIndexes: file_health_health_serice_proto_depIdxs,
	}.Build()
	File_health_health_serice_proto = out.File
	file_health_health_serice_proto_goTypes = nil
	file_health_health_serice_proto_depIdxs = nil
}
